version: 0.2
env:
  variables:
    APP_NAME: heisentechsolutions

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:

  pre_build:
    commands:
      - mvn -B -DskipTests clean package

  build:
    commands:
    #  - mkdir -p target/lambda
    #  - cp target/heisentechsolutions-0.0.1-SNAPSHOT.jar target/lambda/
    #  - cd target/lambda
    #  - zip -r heisentechsolutions-0.0.1-SNAPSHOT.zip heisentechsolutions-0.0.1-SNAPSHOT.jar
    #  - cd ../..
       - mkdir -p target/lambda
       - cp target/heisentechsolutions-0.0.1-SNAPSHOT.jar target/lambda/
       - cd target/lambda
       - pwd
       - ls -la
       - jar xvf heisentechsolutions-0.0.1-SNAPSHOT.jar
       - ls -la
       - rm -rf heisentechsolutions-0.0.1-SNAPSHOT.jar
       - ls -la
       - zip -r heisentechsolutions-0.0.1-SNAPSHOT.zip ./*
       - ls -la
       - cd ../..
       - pwd
       - mv  target/lambda/heisentechsolutions-0.0.1-SNAPSHOT.zip .
       - ls -la

  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - heisentechsolutions-0.0.1-SNAPSHOT.zip
    - appspec.yml